export function isElement(value: any): boolean;
export function isHtmlElement(value: any): boolean;
export function isHtmlElementOfType(value: any, tagName: TagName<any>): boolean;
export function isHtmlAnchorElement(value: any): boolean;
export function isHtmlButtonElement(value: any): boolean;
export function isHtmlLinkElement(value: any): boolean;
export function isHtmlImageElement(value: any): boolean;
export function isHtmlAudioElement(value: any): boolean;
export function isHtmlVideoElement(value: any): boolean;
export function isHtmlInputElement(value: any): boolean;
export function isHtmlTextAreaElement(value: any): boolean;
export function isHtmlCanvasElement(value: any): boolean;
export function isHtmlEmbedElement(value: any): boolean;
export function isHtmlFormElement(value: any): boolean;
export function isHtmlFrameElement(value: any): boolean;
export function isHtmlIFrameElement(value: any): boolean;
export function isHtmlObjectElement(value: any): boolean;
export function isHtmlScriptElement(value: any): boolean;
import { TagName } from "./tagname.js";
