/**
 * ARIA role values.
 */
export type Role = string;
export namespace Role {
    const ALERT: string;
    const ALERTDIALOG: string;
    const APPLICATION: string;
    const ARTICLE: string;
    const BANNER: string;
    const BUTTON: string;
    const CHECKBOX: string;
    const COLUMNHEADER: string;
    const COMBOBOX: string;
    const COMPLEMENTARY: string;
    const CONTENTINFO: string;
    const DEFINITION: string;
    const DIALOG: string;
    const DIRECTORY: string;
    const DOCUMENT: string;
    const FORM: string;
    const GRID: string;
    const GRIDCELL: string;
    const GROUP: string;
    const HEADING: string;
    const IMG: string;
    const LINK: string;
    const LIST: string;
    const LISTBOX: string;
    const LISTITEM: string;
    const LOG: string;
    const MAIN: string;
    const MARQUEE: string;
    const MATH: string;
    const MENU: string;
    const MENUBAR: string;
    const MENU_ITEM: string;
    const MENU_ITEM_CHECKBOX: string;
    const MENU_ITEM_RADIO: string;
    const NAVIGATION: string;
    const NOTE: string;
    const OPTION: string;
    const PRESENTATION: string;
    const PROGRESSBAR: string;
    const RADIO: string;
    const RADIOGROUP: string;
    const REGION: string;
    const ROW: string;
    const ROWGROUP: string;
    const ROWHEADER: string;
    const SCROLLBAR: string;
    const SEARCH: string;
    const SEPARATOR: string;
    const SLIDER: string;
    const SPINBUTTON: string;
    const STATUS: string;
    const TAB: string;
    const TAB_LIST: string;
    const TAB_PANEL: string;
    const TEXTBOX: string;
    const TEXTINFO: string;
    const TIMER: string;
    const TOOLBAR: string;
    const TOOLTIP: string;
    const TREE: string;
    const TREEGRID: string;
    const TREEITEM: string;
}
